backend: 
  nome: github 
  repo: https://github.com/Alexandresl/alexandrelima-dev
  repo-name : master 
  site_domain: alexandrelima.dev
  media_folder: "imagens / uploads"
collections: 
  - name: "post" # Usado em rotas, por exemplo, / admin / collections / blog 
    label: "Post" # Usado na 
    pasta UI : "_posts" # O caminho para a pasta onde os documentos estão armazenados 
    create: true # Permitir que os usuários criem novos documentos neste 
    slug de coleta : "{{year}} - {{month}} - {{day}} - {{slug}}" # modelo de nome de arquivo, ou seja, 
    campos YYYY-MM-DD-title.md : # Os campos de cada documento, normalmente em destaque 
      - {label: "Layout", nome: "layout", widget: "hidden", padrão: "post"} 
      - {label: "Title", name: "title ", widget:" string "} 
      - {label:" Body ", nome:" body ", widget:" markdown "}